### ISSUE TITLE
Install fails - Conflicts with current Jupyterlab dependencies

### ISSUE THREAD

**Issue by packet-rat** [QuantStack/jupyterlab-drawio#10]
Installation fails:  jupyter labextension install jupyterlab-drawio

```
ValueError: 
"jupyterlab-drawio@0.1.2" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLab              Extension            Package
>=0.10.0-0 <0.11.0-0    >=0.15.0-0 <0.16.0-0 @jupyterlab/filebrowser
>=0.10.0-0 <0.11.0-0    >=0.15.0-0 <0.16.0-0 @jupyterlab/launcher
>=0.10.0-0 <0.11.0-0    >=0.15.0-0 <0.16.0-0 @jupyterlab/apputils
>=0.10.0-0 <0.11.0-0    >=0.15.0-0 <0.16.0-0 @jupyterlab/application
```

Full dump
```
jupyter labextension install jupyterlab-drawio
> npm pack jupyterlab-drawio
jupyterlab-drawio-0.1.2.tgz
Traceback (most recent call last):
  File "/Users/xxx/anaconda3/bin/jupyter-labextension", line 11, in <module>
    sys.exit(main())
  File "/Users/xxx/anaconda3/lib/python3.5/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/Users/xxx/anaconda3/lib/python3.5/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/Users/xxx/anaconda3/lib/python3.5/site-packages/jupyterlab/labextensions.py", line 168, in start
    super(LabExtensionApp, self).start()
  File "/Users/xxx/anaconda3/lib/python3.5/site-packages/jupyter_core/application.py", line 256, in start
    self.subapp.start()
  File "/Users/xxx/anaconda3/lib/python3.5/site-packages/jupyterlab/labextensions.py", line 58, in start
    for arg in self.extra_args]
  File "/Users/xxx/anaconda3/lib/python3.5/site-packages/jupyterlab/labextensions.py", line 58, in <listcomp>
    for arg in self.extra_args]
  File "/Users/xxx/anaconda3/lib/python3.5/site-packages/jupyterlab/commands.py", line 100, in install_extension
    return IOLoop.instance().run_sync(func)
  File "/Users/xxx/anaconda3/lib/python3.5/site-packages/tornado/ioloop.py", line 458, in run_sync
    return future_cell[0].result()
  File "/Users/xxx/anaconda3/lib/python3.5/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/Users/xxx/anaconda3/lib/python3.5/site-packages/tornado/gen.py", line 1069, in run
    yielded = self.gen.send(value)
  File "/Users/xxx/anaconda3/lib/python3.5/site-packages/jupyterlab/commands.py", line 158, in install_extension_async
    raise ValueError(msg)
ValueError: 
"jupyterlab-drawio@0.1.2" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLab              Extension            Package
>=0.10.0-0 <0.11.0-0    >=0.15.0-0 <0.16.0-0 @jupyterlab/filebrowser
>=0.10.0-0 <0.11.0-0    >=0.15.0-0 <0.16.0-0 @jupyterlab/launcher
>=0.10.0-0 <0.11.0-0    >=0.15.0-0 <0.16.0-0 @jupyterlab/apputils
>=0.10.0-0 <0.11.0-0    >=0.15.0-0 <0.16.0-0 @jupyterlab/application
```

**Comment by packet-rat** [comment]
Solved:  **conda upgrade jupyterlab**

Note: My bad I thought I had just updated this Anaconda instance  -- so many Condas, Too little time!
