### ISSUE TITLE
Installation hangs on MacOS

### ISSUE THREAD

**Issue by jwayne2978** [QuantStack/jupyterlab-drawio#17]
I am on MacOS 10.13.4. Here are my settings.

* npm 6.0.1
* node 10.0.0
* python 3.6.4
* conda 4.5.3
* pip 10.0.1
* jupyter 4.4.0 (from jupyter --version)
* jupyter 1.0.0 (from pip list | grep jupyter)
* jupyterlab 0.32.1 (pip list)

I followed the installation instructions `jupyter labextension install jupyterlab-drawio` and the for development (clone the repository, then npm install, ....). However, I seem to always get stuck on downloading or processing some `tgz` file. I have no idea what this file is. Using the dev installation method, which I thought would avoid downloading anything since I think it's building from source, it hangs here

```
> node /anaconda3/lib/python3.6/site-packages/jupyterlab/staging/yarn.js install
yarn install v1.5.1
(node:33466) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
info No lockfile found.
[1/4] 🔍  Resolving packages...
jupyterlab-drawio@file:../extensions/jupyterlab-drawio-0.2.0-a7d7cd7f765d8eac5a336096fb87e35a8d84185f.tgz
```

If I hit ctrl-c to break out of this, then I see the following, which is not helpful either.

```
Traceback (most recent call last):
  File "/anaconda3/bin/jupyter-labextension", line 11, in <module>
    sys.exit(main())
  File "/anaconda3/lib/python3.6/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/anaconda3/lib/python3.6/site-packages/jupyterlab/labextensions.py", line 213, in start
    super(LabExtensionApp, self).start()
  File "/anaconda3/lib/python3.6/site-packages/jupyter_core/application.py", line 255, in start
    self.subapp.start()
  File "/anaconda3/lib/python3.6/site-packages/jupyterlab/labextensions.py", line 75, in start
    logger=self.log, command=command)
  File "/anaconda3/lib/python3.6/site-packages/jupyterlab/commands.py", line 259, in build
    command=command, clean_staging=clean_staging)
  File "/anaconda3/lib/python3.6/site-packages/jupyterlab/commands.py", line 400, in build
    self._run(['node', YARN_PATH, 'install'], cwd=staging)
  File "/anaconda3/lib/python3.6/site-packages/jupyterlab/commands.py", line 1278, in _run
    return proc.wait()
  File "/anaconda3/lib/python3.6/site-packages/jupyterlab/process.py", line 108, in wait
    time.sleep(1.)
KeyboardInterrupt
```

I cleared the `pip` and `npm` caches.

* `rm -fr ~/Library/Caches/pip/wheels`
* `rm -fr ~/Library/Caches/pip/http`
* `npm cache clean --force`

None of this helped. 

Any ideas on what's going wrong here?

**Comment by aaliddell** [comment]
I've had the same issue on Ubuntu where it gets stuck in the same step. Using Node 8 instead of Node 10 fixes it, possibly due to this issue: https://github.com/jupyterlab/jupyterlab/issues/4585

**Comment by clstaudt** [comment]
Same issue here:

```
$…  sudo jupyter labextension install jupyterlab-drawio                                                                                                                                                                                                                                                                                                                                                                  15.4m < Wed May 30 17:33:54 2018
                                                  
Password:
> /usr/local/bin/npm pack jupyterlab-drawio
jupyterlab-drawio-0.2.0.tgz
> node /usr/local/lib/python3.6/site-packages/jupyterlab/staging/yarn.js install
yarn install v1.5.1
(node:9230) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
info No lockfile found.
[1/4] 🔍  Resolving packages...
⠐ jupyterlab-drawio@file:../extensions/jupyterlab-drawio-0.2.0.tgz
```
